#!/bin/bash

###############################################################################
# Copyright (c) 2018 Red Hat Inc
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
###############################################################################
#
# input validation
if [ -z "$1" ]; then
    echo "Usage: kill-kube-ns <NAMESPACE>"
    echo "Delete the namespace. kubectl must be logged into the cluster."
    exit
fi

JQ=$(command -v "${BIN_DIR}/jq" || command -v jq)
KUBECTL=$(command -v "${BIN_DIR}/kubectl" || command -v kubectl)

set -eo pipefail

die() { echo "$*" 1>&2 ; exit 1; }

need() {
	command -v "$1" &>/dev/null || die "Binary '$1' is missing but required"
}

# checking pre-reqs
need "curl"

if [[ -z "${JQ}" ]]; then
  die "jq is missing but required"
fi
if [[ -z "${KUBECTL}" ]]; then
  die "kubectl is missing but required"
fi

PROJECT="$1"
shift

test -n "$PROJECT" || die "Missing arguments: kill-ns <namespace>"

${KUBECTL} proxy &>/dev/null &
PROXY_PID=$!
killproxy () {
	kill $PROXY_PID
}
trap killproxy EXIT

sleep 1 # give the proxy a second

${KUBECTL} get namespace "$PROJECT" -o json | ${JQ} 'del(.spec.finalizers[] | select("kubernetes"))' | curl -s -k -H "Content-Type: application/json" -X PUT -o /dev/null --data-binary @- http://localhost:8001/api/v1/namespaces/$PROJECT/finalize && echo "Killed namespace: $PROJECT"

# proxy will get killed by the trap
